name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: add execute permission to gradlew
        run: chmod u+x ./gradlew
      - name: Assemble debug apk
        run: ./gradlew assembleDebug
      - name: run tests
        run: ./gradlew test
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

